# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_rayleigh3D.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(737, 551)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mplwidget3D = MPL_WIDGET_3D(self.centralWidget)
        self.mplwidget3D.setObjectName("mplwidget3D")
        self.horizontalLayout.addWidget(self.mplwidget3D)
        MainWindow.setCentralWidget(self.centralWidget)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.dockWidgetContents_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_lamda = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_lamda.setObjectName("label_lamda")
        self.verticalLayout.addWidget(self.label_lamda)
        self.SpinBox_lambda = QtWidgets.QSpinBox(self.dockWidgetContents_3)
        self.SpinBox_lambda.setMinimum(400)
        self.SpinBox_lambda.setMaximum(900)
        self.SpinBox_lambda.setSingleStep(10)
        self.SpinBox_lambda.setProperty("value", 560)
        self.SpinBox_lambda.setObjectName("SpinBox_lambda")
        self.verticalLayout.addWidget(self.SpinBox_lambda)
        self.slider_lambda = QtWidgets.QSlider(self.dockWidgetContents_3)
        self.slider_lambda.setMinimum(400)
        self.slider_lambda.setMaximum(900)
        self.slider_lambda.setSingleStep(10)
        self.slider_lambda.setProperty("value", 560)
        self.slider_lambda.setOrientation(QtCore.Qt.Horizontal)
        self.slider_lambda.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_lambda.setTickInterval(50)
        self.slider_lambda.setObjectName("slider_lambda")
        self.verticalLayout.addWidget(self.slider_lambda)
        spacerItem = QtWidgets.QSpacerItem(105, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_a = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_a.setObjectName("label_a")
        self.verticalLayout.addWidget(self.label_a)
        self.SpinBox_a = QtWidgets.QDoubleSpinBox(self.dockWidgetContents_3)
        self.SpinBox_a.setDecimals(3)
        self.SpinBox_a.setMinimum(0.0)
        self.SpinBox_a.setMaximum(1000.0)
        self.SpinBox_a.setSingleStep(1.0)
        self.SpinBox_a.setProperty("value", 52.0)
        self.SpinBox_a.setObjectName("SpinBox_a")
        self.verticalLayout.addWidget(self.SpinBox_a)
        self.slider_a = QtWidgets.QSlider(self.dockWidgetContents_3)
        self.slider_a.setMinimum(0)
        self.slider_a.setMaximum(1000)
        self.slider_a.setSingleStep(20)
        self.slider_a.setPageStep(1)
        self.slider_a.setProperty("value", 52)
        self.slider_a.setSliderPosition(52)
        self.slider_a.setOrientation(QtCore.Qt.Horizontal)
        self.slider_a.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_a.setTickInterval(50)
        self.slider_a.setObjectName("slider_a")
        self.verticalLayout.addWidget(self.slider_a)
        spacerItem1 = QtWidgets.QSpacerItem(105, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_d = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_d.setObjectName("label_d")
        self.verticalLayout.addWidget(self.label_d)
        self.SpinBox_d = QtWidgets.QDoubleSpinBox(self.dockWidgetContents_3)
        self.SpinBox_d.setDecimals(3)
        self.SpinBox_d.setMaximum(20.0)
        self.SpinBox_d.setSingleStep(0.1)
        self.SpinBox_d.setProperty("value", 7.0)
        self.SpinBox_d.setObjectName("SpinBox_d")
        self.verticalLayout.addWidget(self.SpinBox_d)
        self.slider_d = QtWidgets.QSlider(self.dockWidgetContents_3)
        self.slider_d.setMaximum(20)
        self.slider_d.setSingleStep(1)
        self.slider_d.setPageStep(1)
        self.slider_d.setProperty("value", 7)
        self.slider_d.setOrientation(QtCore.Qt.Horizontal)
        self.slider_d.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_d.setTickInterval(1)
        self.slider_d.setObjectName("slider_d")
        self.verticalLayout.addWidget(self.slider_d)
        spacerItem2 = QtWidgets.QSpacerItem(105, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_e = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_e.setObjectName("label_e")
        self.verticalLayout.addWidget(self.label_e)
        self.SpinBox_e = QtWidgets.QDoubleSpinBox(self.dockWidgetContents_3)
        self.SpinBox_e.setDecimals(1)
        self.SpinBox_e.setMinimum(0.1)
        self.SpinBox_e.setSingleStep(1.0)
        self.SpinBox_e.setProperty("value", 10.0)
        self.SpinBox_e.setObjectName("SpinBox_e")
        self.verticalLayout.addWidget(self.SpinBox_e)
        self.slider_e = QtWidgets.QSlider(self.dockWidgetContents_3)
        self.slider_e.setMinimum(1)
        self.slider_e.setMaximum(100)
        self.slider_e.setProperty("value", 10)
        self.slider_e.setOrientation(QtCore.Qt.Horizontal)
        self.slider_e.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_e.setTickInterval(10)
        self.slider_e.setObjectName("slider_e")
        self.verticalLayout.addWidget(self.slider_e)
        spacerItem3 = QtWidgets.QSpacerItem(105, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.label_f2 = QtWidgets.QLabel(self.dockWidgetContents_3)
        self.label_f2.setObjectName("label_f2")
        self.verticalLayout.addWidget(self.label_f2)
        self.SpinBox_f2 = QtWidgets.QDoubleSpinBox(self.dockWidgetContents_3)
        self.SpinBox_f2.setDecimals(1)
        self.SpinBox_f2.setMinimum(0.1)
        self.SpinBox_f2.setMaximum(50.0)
        self.SpinBox_f2.setProperty("value", 2.0)
        self.SpinBox_f2.setObjectName("SpinBox_f2")
        self.verticalLayout.addWidget(self.SpinBox_f2)
        self.slider_f2 = QtWidgets.QSlider(self.dockWidgetContents_3)
        self.slider_f2.setMinimum(1)
        self.slider_f2.setMaximum(50)
        self.slider_f2.setProperty("value", 2)
        self.slider_f2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_f2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_f2.setTickInterval(10)
        self.slider_f2.setObjectName("slider_f2")
        self.verticalLayout.addWidget(self.slider_f2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.dockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 737, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Diffraction - Fraunhofer"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Setting"))
        self.label_lamda.setText(_translate("MainWindow", "Wave length(10e-9 m)"))
        self.SpinBox_lambda.setStatusTip(_translate("MainWindow", "Change the wave length of monochromatic light"))
        self.slider_lambda.setStatusTip(_translate("MainWindow", "Change the wave length of monochromatic light"))
        self.label_a.setText(_translate("MainWindow", "a(10e-6 m)"))
        self.SpinBox_a.setStatusTip(_translate("MainWindow", "Change the radius  of the circular aperture"))
        self.slider_a.setStatusTip(_translate("MainWindow", "Change the radius  of the circular aperture"))
        self.label_d.setText(_translate("MainWindow", "d(10e-3)"))
        self.SpinBox_d.setStatusTip(_translate("MainWindow", "Distance of the source from the optic axis"))
        self.slider_d.setStatusTip(_translate("MainWindow", "Distance of the source from the optic axis"))
        self.label_e.setText(_translate("MainWindow", "e(10e-2 m)"))
        self.SpinBox_e.setStatusTip(_translate("MainWindow", "Change the side of the square-shaped screen"))
        self.slider_e.setStatusTip(_translate("MainWindow", "Change the side of the square-shaped screen"))
        self.label_f2.setText(_translate("MainWindow", "f2(m)"))
        self.SpinBox_f2.setStatusTip(_translate("MainWindow", "Change the focal length f2 of the lens L2"))
        self.slider_f2.setStatusTip(_translate("MainWindow", "Change the focal length f2 of the lens L2"))

from mplwidget import MPL_WIDGET_3D
