# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_FresnelBiprism.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(917, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SpinBox_Index = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_Index.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_Index.setSuffix("")
        self.SpinBox_Index.setDecimals(3)
        self.SpinBox_Index.setMaximum(5.0)
        self.SpinBox_Index.setSingleStep(0.001)
        self.SpinBox_Index.setProperty("value", 1.5)
        self.SpinBox_Index.setObjectName("SpinBox_Index")
        self.gridLayout_2.addWidget(self.SpinBox_Index, 0, 7, 1, 1)
        self.SpinBox_Source1 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_Source1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_Source1.setSuffix("")
        self.SpinBox_Source1.setDecimals(3)
        self.SpinBox_Source1.setMinimum(0.0)
        self.SpinBox_Source1.setMaximum(100.0)
        self.SpinBox_Source1.setSingleStep(0.1)
        self.SpinBox_Source1.setProperty("value", 0.0)
        self.SpinBox_Source1.setObjectName("SpinBox_Source1")
        self.gridLayout_2.addWidget(self.SpinBox_Source1, 0, 2, 1, 1)
        self.SpinBox_a = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_a.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_a.setSuffix("")
        self.SpinBox_a.setDecimals(3)
        self.SpinBox_a.setMaximum(10.0)
        self.SpinBox_a.setSingleStep(0.001)
        self.SpinBox_a.setProperty("value", 0.5)
        self.SpinBox_a.setObjectName("SpinBox_a")
        self.gridLayout_2.addWidget(self.SpinBox_a, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.SpinBox_Height = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_Height.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_Height.setSuffix("")
        self.SpinBox_Height.setDecimals(3)
        self.SpinBox_Height.setMaximum(5.0)
        self.SpinBox_Height.setSingleStep(0.01)
        self.SpinBox_Height.setProperty("value", 1.0)
        self.SpinBox_Height.setObjectName("SpinBox_Height")
        self.gridLayout_2.addWidget(self.SpinBox_Height, 2, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 8, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 6, 1, 1)
        self.SpinBox_Angle = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_Angle.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_Angle.setDecimals(3)
        self.SpinBox_Angle.setMaximum(100.0)
        self.SpinBox_Angle.setSingleStep(0.01)
        self.SpinBox_Angle.setProperty("value", 8.7)
        self.SpinBox_Angle.setObjectName("SpinBox_Angle")
        self.gridLayout_2.addWidget(self.SpinBox_Angle, 1, 7, 1, 1)
        self.SpinBox_D = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_D.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_D.setDecimals(3)
        self.SpinBox_D.setMaximum(10.0)
        self.SpinBox_D.setSingleStep(0.01)
        self.SpinBox_D.setProperty("value", 2.0)
        self.SpinBox_D.setObjectName("SpinBox_D")
        self.gridLayout_2.addWidget(self.SpinBox_D, 1, 9, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 8, 1, 1)
        self.SpinBox_Source2 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_Source2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_Source2.setDecimals(3)
        self.SpinBox_Source2.setMaximum(100.0)
        self.SpinBox_Source2.setSingleStep(0.1)
        self.SpinBox_Source2.setObjectName("SpinBox_Source2")
        self.gridLayout_2.addWidget(self.SpinBox_Source2, 1, 2, 1, 1)
        self.SpinBox_Lambda = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_Lambda.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_Lambda.setMinimum(200.0)
        self.SpinBox_Lambda.setMaximum(1000.0)
        self.SpinBox_Lambda.setProperty("value", 632.0)
        self.SpinBox_Lambda.setObjectName("SpinBox_Lambda")
        self.gridLayout_2.addWidget(self.SpinBox_Lambda, 0, 9, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.mplwidget = MPL_WIDGET_2D(self.centralWidget)
        self.mplwidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.mplwidget.setObjectName("mplwidget")
        self.verticalLayout.addWidget(self.mplwidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fresnel Biprism"))
        self.label_3.setText(_translate("MainWindow", "Source-Prism distance (m)"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Slit source 1 width (μm)</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Refractive Index"))
        self.label_8.setText(_translate("MainWindow", "Screen distance (m)"))
        self.label_4.setText(_translate("MainWindow", "Prism\'s height (cm)"))
        self.label_6.setText(_translate("MainWindow", "Prism\'s Angle (mrad)"))
        self.label_5.setText(_translate("MainWindow", "Slit source 2 width (μm)"))
        self.label_7.setText(_translate("MainWindow", "Wavelength (nm)"))

from mplwidget import MPL_WIDGET_2D
