# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_FresnelMirror.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(917, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SpinBox_LambdaR = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_LambdaR.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_LambdaR.setSuffix("")
        self.SpinBox_LambdaR.setDecimals(3)
        self.SpinBox_LambdaR.setMinimum(100.0)
        self.SpinBox_LambdaR.setMaximum(2000.0)
        self.SpinBox_LambdaR.setSingleStep(0.1)
        self.SpinBox_LambdaR.setProperty("value", 650.0)
        self.SpinBox_LambdaR.setObjectName("SpinBox_LambdaR")
        self.gridLayout_2.addWidget(self.SpinBox_LambdaR, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.SpinBox_LambdaO = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_LambdaO.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_LambdaO.setDecimals(3)
        self.SpinBox_LambdaO.setMinimum(100.0)
        self.SpinBox_LambdaO.setMaximum(2000.0)
        self.SpinBox_LambdaO.setSingleStep(0.1)
        self.SpinBox_LambdaO.setProperty("value", 610.0)
        self.SpinBox_LambdaO.setObjectName("SpinBox_LambdaO")
        self.gridLayout_2.addWidget(self.SpinBox_LambdaO, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 1, 1, 1)
        self.SpinBox_LambdaY = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_LambdaY.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_LambdaY.setDecimals(3)
        self.SpinBox_LambdaY.setMinimum(100.0)
        self.SpinBox_LambdaY.setMaximum(2000.0)
        self.SpinBox_LambdaY.setSingleStep(0.1)
        self.SpinBox_LambdaY.setProperty("value", 580.0)
        self.SpinBox_LambdaY.setObjectName("SpinBox_LambdaY")
        self.gridLayout_2.addWidget(self.SpinBox_LambdaY, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 9, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 6, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 1, 1, 1)
        self.SpinBox_Angle = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_Angle.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_Angle.setSuffix("")
        self.SpinBox_Angle.setDecimals(3)
        self.SpinBox_Angle.setMaximum(5.0)
        self.SpinBox_Angle.setSingleStep(0.001)
        self.SpinBox_Angle.setProperty("value", 5.0)
        self.SpinBox_Angle.setObjectName("SpinBox_Angle")
        self.gridLayout_2.addWidget(self.SpinBox_Angle, 0, 10, 1, 1)
        self.SpinBox_LambdaG = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_LambdaG.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_LambdaG.setDecimals(3)
        self.SpinBox_LambdaG.setMinimum(100.0)
        self.SpinBox_LambdaG.setMaximum(2000.0)
        self.SpinBox_LambdaG.setSingleStep(0.1)
        self.SpinBox_LambdaG.setProperty("value", 530.0)
        self.SpinBox_LambdaG.setObjectName("SpinBox_LambdaG")
        self.gridLayout_2.addWidget(self.SpinBox_LambdaG, 0, 7, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 8, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 9, 1, 1)
        self.SpinBox_a = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_a.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_a.setSuffix("")
        self.SpinBox_a.setDecimals(3)
        self.SpinBox_a.setMaximum(1000.0)
        self.SpinBox_a.setSingleStep(0.05)
        self.SpinBox_a.setProperty("value", 800.0)
        self.SpinBox_a.setObjectName("SpinBox_a")
        self.gridLayout_2.addWidget(self.SpinBox_a, 1, 10, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 9, 1, 1)
        self.SpinBox_D = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_D.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_D.setSuffix("")
        self.SpinBox_D.setDecimals(3)
        self.SpinBox_D.setMaximum(10.0)
        self.SpinBox_D.setSingleStep(0.1)
        self.SpinBox_D.setProperty("value", 1.2)
        self.SpinBox_D.setObjectName("SpinBox_D")
        self.gridLayout_2.addWidget(self.SpinBox_D, 2, 10, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 6, 1, 1)
        self.SpinBox_LambdaB = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_LambdaB.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_LambdaB.setDecimals(3)
        self.SpinBox_LambdaB.setMinimum(100.0)
        self.SpinBox_LambdaB.setMaximum(2000.0)
        self.SpinBox_LambdaB.setSingleStep(0.1)
        self.SpinBox_LambdaB.setProperty("value", 470.0)
        self.SpinBox_LambdaB.setObjectName("SpinBox_LambdaB")
        self.gridLayout_2.addWidget(self.SpinBox_LambdaB, 1, 7, 1, 1)
        self.SpinBox_LambdaP = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_LambdaP.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_LambdaP.setDecimals(3)
        self.SpinBox_LambdaP.setMinimum(100.0)
        self.SpinBox_LambdaP.setMaximum(2000.0)
        self.SpinBox_LambdaP.setSingleStep(0.1)
        self.SpinBox_LambdaP.setProperty("value", 420.0)
        self.SpinBox_LambdaP.setObjectName("SpinBox_LambdaP")
        self.gridLayout_2.addWidget(self.SpinBox_LambdaP, 2, 7, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 11, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.mplwidget = MPL_WIDGET_2D(self.centralWidget)
        self.mplwidget.setObjectName("mplwidget")
        self.verticalLayout.addWidget(self.mplwidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FresnelMirror"))
        self.label.setText(_translate("MainWindow", "Wavelength Red (nm)"))
        self.label_5.setText(_translate("MainWindow", "Wavelength Orange(nm)"))
        self.label_2.setText(_translate("MainWindow", "Angle between mirrors (mrad)"))
        self.label_7.setText(_translate("MainWindow", "Wavelength Green (nm)"))
        self.label_6.setText(_translate("MainWindow", "Wavelength Yellow(nm)"))
        self.label_3.setText(_translate("MainWindow", "Distance Source-Mirror (mm)"))
        self.label_4.setText(_translate("MainWindow", "Distance from the screen (m)"))
        self.label_8.setText(_translate("MainWindow", "Wavelength Blue (nm)"))
        self.label_9.setText(_translate("MainWindow", "Wavelength Purple(nm)"))

from mplwidget import MPL_WIDGET_2D
