# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Gaussian.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(917, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 10, 1, 1)
        self.SpinBox_Lambda = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_Lambda.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_Lambda.setSuffix("")
        self.SpinBox_Lambda.setDecimals(3)
        self.SpinBox_Lambda.setMinimum(100.0)
        self.SpinBox_Lambda.setMaximum(2000.0)
        self.SpinBox_Lambda.setSingleStep(0.1)
        self.SpinBox_Lambda.setProperty("value", 545.0)
        self.SpinBox_Lambda.setObjectName("SpinBox_Lambda")
        self.gridLayout_2.addWidget(self.SpinBox_Lambda, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.SpinBox_a = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_a.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_a.setDecimals(3)
        self.SpinBox_a.setMinimum(0.0)
        self.SpinBox_a.setMaximum(20.0)
        self.SpinBox_a.setSingleStep(0.1)
        self.SpinBox_a.setProperty("value", 1.0)
        self.SpinBox_a.setObjectName("SpinBox_a")
        self.gridLayout_2.addWidget(self.SpinBox_a, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 7, 1, 1)
        self.SpinBox_Angle = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_Angle.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_Angle.setSuffix("")
        self.SpinBox_Angle.setDecimals(3)
        self.SpinBox_Angle.setMaximum(5.0)
        self.SpinBox_Angle.setSingleStep(0.001)
        self.SpinBox_Angle.setProperty("value", 0.0)
        self.SpinBox_Angle.setObjectName("SpinBox_Angle")
        self.gridLayout_2.addWidget(self.SpinBox_Angle, 0, 8, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 6, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 7, 1, 1)
        self.SpinBox_e = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_e.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_e.setSuffix("")
        self.SpinBox_e.setDecimals(3)
        self.SpinBox_e.setMaximum(100.0)
        self.SpinBox_e.setSingleStep(0.05)
        self.SpinBox_e.setProperty("value", 10.0)
        self.SpinBox_e.setObjectName("SpinBox_e")
        self.gridLayout_2.addWidget(self.SpinBox_e, 1, 8, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 9, 1, 1)
        self.Slider_a = QtWidgets.QSlider(self.centralWidget)
        self.Slider_a.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.Slider_a.setMaximum(20)
        self.Slider_a.setProperty("value", 1)
        self.Slider_a.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_a.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_a.setTickInterval(5)
        self.Slider_a.setObjectName("Slider_a")
        self.gridLayout_2.addWidget(self.Slider_a, 2, 1, 1, 1)
        self.lineEdit_Lc = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_Lc.setObjectName("lineEdit_Lc")
        self.gridLayout_2.addWidget(self.lineEdit_Lc, 0, 11, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 10, 1, 1)
        self.lineEdit_Contraste = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_Contraste.setObjectName("lineEdit_Contraste")
        self.gridLayout_2.addWidget(self.lineEdit_Contraste, 1, 11, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.mplwidget = MPL_WIDGET_2D(self.centralWidget)
        self.mplwidget.setObjectName("mplwidget")
        self.verticalLayout.addWidget(self.mplwidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gaussian"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff100b;\">Coherence length Lc(µm)</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Wavelength (nm)"))
        self.label_5.setText(_translate("MainWindow", "Ray\'s width b(nm)"))
        self.label_2.setText(_translate("MainWindow", "Incidente angle (rad)"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Blade\'s thickness e(μm)</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0606;\">Contraste at Lc</span></p></body></html>"))

from mplwidget import MPL_WIDGET_2D
