# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_superpose.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(871, 731)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 6, 1, 1)
        self.spinBox_NT = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_NT.setMinimum(1)
        self.spinBox_NT.setMaximum(100)
        self.spinBox_NT.setProperty("value", 20)
        self.spinBox_NT.setObjectName("spinBox_NT")
        self.gridLayout.addWidget(self.spinBox_NT, 2, 7, 1, 1)
        self.spinBox_amp1 = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_amp1.setMinimum(1)
        self.spinBox_amp1.setMaximum(10)
        self.spinBox_amp1.setObjectName("spinBox_amp1")
        self.gridLayout.addWidget(self.spinBox_amp1, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.label_Lambda1 = QtWidgets.QLabel(self.centralWidget)
        self.label_Lambda1.setObjectName("label_Lambda1")
        self.gridLayout.addWidget(self.label_Lambda1, 0, 0, 1, 1)
        self.spinBox_PhShiftR = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_PhShiftR.setMaximum(360)
        self.spinBox_PhShiftR.setObjectName("spinBox_PhShiftR")
        self.gridLayout.addWidget(self.spinBox_PhShiftR, 1, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.spinBox_Lambda1 = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_Lambda1.setMinimum(400)
        self.spinBox_Lambda1.setMaximum(800)
        self.spinBox_Lambda1.setProperty("value", 450)
        self.spinBox_Lambda1.setObjectName("spinBox_Lambda1")
        self.gridLayout.addWidget(self.spinBox_Lambda1, 0, 1, 1, 1)
        self.spinBox_PhShiftC = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_PhShiftC.setMaximum(360)
        self.spinBox_PhShiftC.setObjectName("spinBox_PhShiftC")
        self.gridLayout.addWidget(self.spinBox_PhShiftC, 0, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 6, 1, 1)
        self.spinBox_Alpha = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_Alpha.setMaximum(180)
        self.spinBox_Alpha.setObjectName("spinBox_Alpha")
        self.gridLayout.addWidget(self.spinBox_Alpha, 0, 7, 1, 1)
        self.lineEdit_contrast = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_contrast.setObjectName("lineEdit_contrast")
        self.gridLayout.addWidget(self.lineEdit_contrast, 2, 1, 1, 1)
        self.spinBox_Lambda2 = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_Lambda2.setMinimum(400)
        self.spinBox_Lambda2.setMaximum(800)
        self.spinBox_Lambda2.setProperty("value", 650)
        self.spinBox_Lambda2.setObjectName("spinBox_Lambda2")
        self.gridLayout.addWidget(self.spinBox_Lambda2, 1, 1, 1, 1)
        self.spinBox_amp2 = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_amp2.setMinimum(1)
        self.spinBox_amp2.setMaximum(10)
        self.spinBox_amp2.setObjectName("spinBox_amp2")
        self.gridLayout.addWidget(self.spinBox_amp2, 1, 3, 1, 1)
        self.label_Lambda2 = QtWidgets.QLabel(self.centralWidget)
        self.label_Lambda2.setObjectName("label_Lambda2")
        self.gridLayout.addWidget(self.label_Lambda2, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.mplwidget1 = MPL_WIDGET_2D(self.centralWidget)
        self.mplwidget1.setObjectName("mplwidget1")
        self.verticalLayout.addWidget(self.mplwidget1)
        self.mplwidget2 = MPL_WIDGET_2D(self.centralWidget)
        self.mplwidget2.setObjectName("mplwidget2")
        self.verticalLayout.addWidget(self.mplwidget2)
        self.mplwidget3 = MPL_WIDGET_2D(self.centralWidget)
        self.mplwidget3.setObjectName("mplwidget3")
        self.verticalLayout.addWidget(self.mplwidget3)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Superposition"))
        self.label_8.setText(_translate("MainWindow", "Number of periods"))
        self.label.setText(_translate("MainWindow", "Amplitude (E1) (a.u)"))
        self.label_Lambda1.setText(_translate("MainWindow", "Wavelength (wave1) (nm)"))
        self.label_4.setText(_translate("MainWindow", "Random phase shift (°)"))
        self.label_9.setText(_translate("MainWindow", "Contrast"))
        self.label_3.setText(_translate("MainWindow", "Constant phase shift (°)"))
        self.label_7.setText(_translate("MainWindow", "Angle from wave1 (°)"))
        self.label_Lambda2.setText(_translate("MainWindow", "Wavelength (wave2) (nm)"))
        self.label_2.setText(_translate("MainWindow", "Amplitude (E2) (a.u)"))

from mplwidget import MPL_WIDGET_2D
