# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_FabryPerot.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 636)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Lambda2 = QtWidgets.QLabel(self.centralWidget)
        self.label_Lambda2.setObjectName("label_Lambda2")
        self.gridLayout_2.addWidget(self.label_Lambda2, 1, 3, 1, 1)
        self.SpinBox_Lambda1 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_Lambda1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_Lambda1.setDecimals(2)
        self.SpinBox_Lambda1.setMinimum(300.0)
        self.SpinBox_Lambda1.setMaximum(520.0)
        self.SpinBox_Lambda1.setSingleStep(0.01)
        self.SpinBox_Lambda1.setProperty("value", 499.7)
        self.SpinBox_Lambda1.setObjectName("SpinBox_Lambda1")
        self.gridLayout_2.addWidget(self.SpinBox_Lambda1, 0, 4, 1, 1)
        self.label_Lambda1 = QtWidgets.QLabel(self.centralWidget)
        self.label_Lambda1.setObjectName("label_Lambda1")
        self.gridLayout_2.addWidget(self.label_Lambda1, 0, 3, 1, 1)
        self.cbg = QtWidgets.QCheckBox(self.centralWidget)
        self.cbg.setChecked(True)
        self.cbg.setObjectName("cbg")
        self.gridLayout_2.addWidget(self.cbg, 1, 5, 1, 1)
        self.pushButton_Lambda1 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Lambda1.setObjectName("pushButton_Lambda1")
        self.gridLayout_2.addWidget(self.pushButton_Lambda1, 0, 8, 1, 1)
        self.SpinBox_Lambda2 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_Lambda2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_Lambda2.setDecimals(2)
        self.SpinBox_Lambda2.setMinimum(480.0)
        self.SpinBox_Lambda2.setMaximum(564.0)
        self.SpinBox_Lambda2.setSingleStep(0.01)
        self.SpinBox_Lambda2.setProperty("value", 499.9)
        self.SpinBox_Lambda2.setObjectName("SpinBox_Lambda2")
        self.gridLayout_2.addWidget(self.SpinBox_Lambda2, 1, 4, 1, 1)
        self.cbb = QtWidgets.QCheckBox(self.centralWidget)
        self.cbb.setChecked(True)
        self.cbb.setObjectName("cbb")
        self.gridLayout_2.addWidget(self.cbb, 0, 5, 1, 1)
        self.SpinBox_e = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_e.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_e.setSuffix("")
        self.SpinBox_e.setDecimals(2)
        self.SpinBox_e.setMinimum(100.0)
        self.SpinBox_e.setMaximum(5000.0)
        self.SpinBox_e.setSingleStep(0.01)
        self.SpinBox_e.setProperty("value", 500.0)
        self.SpinBox_e.setObjectName("SpinBox_e")
        self.gridLayout_2.addWidget(self.SpinBox_e, 1, 2, 1, 1)
        self.SpinBox_angle = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_angle.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_angle.setSuffix("")
        self.SpinBox_angle.setDecimals(2)
        self.SpinBox_angle.setMaximum(0.5)
        self.SpinBox_angle.setSingleStep(0.01)
        self.SpinBox_angle.setProperty("value", 0.04)
        self.SpinBox_angle.setObjectName("SpinBox_angle")
        self.gridLayout_2.addWidget(self.SpinBox_angle, 0, 2, 1, 1)
        self.label_angle = QtWidgets.QLabel(self.centralWidget)
        self.label_angle.setObjectName("label_angle")
        self.gridLayout_2.addWidget(self.label_angle, 0, 1, 1, 1)
        self.label_e = QtWidgets.QLabel(self.centralWidget)
        self.label_e.setObjectName("label_e")
        self.gridLayout_2.addWidget(self.label_e, 1, 1, 1, 1)
        self.cbr = QtWidgets.QCheckBox(self.centralWidget)
        self.cbr.setChecked(True)
        self.cbr.setAutoRepeat(False)
        self.cbr.setAutoExclusive(False)
        self.cbr.setObjectName("cbr")
        self.gridLayout_2.addWidget(self.cbr, 2, 5, 1, 1)
        self.pushButton_Lambda2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Lambda2.setObjectName("pushButton_Lambda2")
        self.gridLayout_2.addWidget(self.pushButton_Lambda2, 1, 8, 1, 1)
        self.pushButton_Lambda3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Lambda3.setObjectName("pushButton_Lambda3")
        self.gridLayout_2.addWidget(self.pushButton_Lambda3, 2, 8, 1, 1)
        self.label_na = QtWidgets.QLabel(self.centralWidget)
        self.label_na.setObjectName("label_na")
        self.gridLayout_2.addWidget(self.label_na, 1, 6, 1, 1)
        self.label_nt = QtWidgets.QLabel(self.centralWidget)
        self.label_nt.setObjectName("label_nt")
        self.gridLayout_2.addWidget(self.label_nt, 2, 6, 1, 1)
        self.SpinBox_nr = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_nr.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_nr.setMaximum(1.0)
        self.SpinBox_nr.setSingleStep(0.01)
        self.SpinBox_nr.setProperty("value", 0.9)
        self.SpinBox_nr.setObjectName("SpinBox_nr")
        self.gridLayout_2.addWidget(self.SpinBox_nr, 0, 7, 1, 1)
        self.SpinBox_nt = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_nt.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_nt.setDecimals(5)
        self.SpinBox_nt.setMaximum(2.0)
        self.SpinBox_nt.setSingleStep(1e-05)
        self.SpinBox_nt.setProperty("value", 1.0)
        self.SpinBox_nt.setObjectName("SpinBox_nt")
        self.gridLayout_2.addWidget(self.SpinBox_nt, 2, 7, 1, 1)
        self.label_nr = QtWidgets.QLabel(self.centralWidget)
        self.label_nr.setObjectName("label_nr")
        self.gridLayout_2.addWidget(self.label_nr, 0, 6, 1, 1)
        self.SpinBox_na = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_na.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_na.setDecimals(3)
        self.SpinBox_na.setMaximum(1.0)
        self.SpinBox_na.setSingleStep(0.001)
        self.SpinBox_na.setProperty("value", 0.0)
        self.SpinBox_na.setObjectName("SpinBox_na")
        self.gridLayout_2.addWidget(self.SpinBox_na, 1, 7, 1, 1)
        self.label_Lambda3 = QtWidgets.QLabel(self.centralWidget)
        self.label_Lambda3.setObjectName("label_Lambda3")
        self.gridLayout_2.addWidget(self.label_Lambda3, 2, 3, 1, 1)
        self.SpinBox_Lambda3 = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.SpinBox_Lambda3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_Lambda3.setSuffix("")
        self.SpinBox_Lambda3.setDecimals(2)
        self.SpinBox_Lambda3.setMinimum(490.0)
        self.SpinBox_Lambda3.setMaximum(800.0)
        self.SpinBox_Lambda3.setSingleStep(0.01)
        self.SpinBox_Lambda3.setProperty("value", 500.0)
        self.SpinBox_Lambda3.setObjectName("SpinBox_Lambda3")
        self.gridLayout_2.addWidget(self.SpinBox_Lambda3, 2, 4, 1, 1)
        self.pushButton_Lambda123 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Lambda123.setObjectName("pushButton_Lambda123")
        self.gridLayout_2.addWidget(self.pushButton_Lambda123, 3, 8, 1, 1)
        self.Slider_e = QtWidgets.QSlider(self.centralWidget)
        self.Slider_e.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.Slider_e.setMaximum(5000)
        self.Slider_e.setSingleStep(1)
        self.Slider_e.setPageStep(1)
        self.Slider_e.setProperty("value", 2000)
        self.Slider_e.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_e.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.Slider_e.setTickInterval(200)
        self.Slider_e.setObjectName("Slider_e")
        self.gridLayout_2.addWidget(self.Slider_e, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mplwidget1 = MPL_WIDGET_2D(self.tab)
        self.mplwidget1.setObjectName("mplwidget1")
        self.horizontalLayout.addWidget(self.mplwidget1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.mplwidget2 = MPL_WIDGET_2D(self.tab_4)
        self.mplwidget2.setObjectName("mplwidget2")
        self.horizontalLayout_3.addWidget(self.mplwidget2)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.mplwidget3 = MPL_WIDGET_2D(self.tab_3)
        self.mplwidget3.setObjectName("mplwidget3")
        self.horizontalLayout_5.addWidget(self.mplwidget3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mplwidget4 = MPL_WIDGET_2D(self.tab_2)
        self.mplwidget4.setObjectName("mplwidget4")
        self.horizontalLayout_2.addWidget(self.mplwidget4)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fabry Perot"))
        self.label_Lambda2.setText(_translate("MainWindow", "Wavelength Green (nm)"))
        self.label_Lambda1.setText(_translate("MainWindow", "Wavelength Blue (nm)"))
        self.cbg.setText(_translate("MainWindow", "View Green"))
        self.pushButton_Lambda1.setText(_translate("MainWindow", "Blue light"))
        self.cbb.setText(_translate("MainWindow", "View Blue"))
        self.label_angle.setText(_translate("MainWindow", "Angle maximum (rad)"))
        self.label_e.setText(_translate("MainWindow", "<html><head/><body><p>Thickness (&micro;m)</p></body></html>"))
        self.cbr.setText(_translate("MainWindow", "View Red"))
        self.pushButton_Lambda2.setText(_translate("MainWindow", "Green light"))
        self.pushButton_Lambda3.setText(_translate("MainWindow", "Red light"))
        self.label_na.setText(_translate("MainWindow", "Absorption coefficient"))
        self.label_nt.setText(_translate("MainWindow", "Refraction Index"))
        self.label_nr.setText(_translate("MainWindow", "Reflection coefficient"))
        self.label_Lambda3.setText(_translate("MainWindow", "Wavelength Red (nm)"))
        self.pushButton_Lambda123.setText(_translate("MainWindow", "Wight light"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Theta"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Order"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Phase"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Wavenember"))

from mplwidget import MPL_WIDGET_2D
